# Generated by Django 3.2 on 2021-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_title', models.CharField(max_length=100)),
                ('proj_category', models.CharField(max_length=100)),
                ('mem1_name', models.CharField(max_length=100)),
                ('mem2_name', models.CharField(max_length=100)),
                ('mem3_name', models.CharField(max_length=100)),
                ('mem1_linkedin', models.CharField(max_length=100)),
                ('mem2_linkedin', models.CharField(max_length=100)),
                ('mem3_linkedin', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=11)),
                ('proj_description', models.TextField()),
            ],
        ),
    ]
