# Generated by Django 3.2 on 2021-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_project_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_category',
            field=models.CharField(choices=[('pro_dev', 'PRODUCT DEVELOPMENT'), ('research', 'RESEARCH BASED'), ('env_sust', 'ENVIRONMENT SUSTAINABILITY')], default='pro_dev', max_length=50),
        ),
    ]
