# Generated by Django 3.2 on 2021-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_alter_project_proj_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_category',
            field=models.CharField(choices=[('PRODUCT DEVELOPMENT', 'PRODUCT DEVELOPMENT'), ('RESEARCH BASED', 'RESEARCH BASED'), ('ENVIRONMENT SUSTAINABILITY', 'ENVIRONMENT SUSTAINABILITY')], default='PRODUCT DEVELOPMENT', max_length=50),
        ),
    ]
