# Generated by Django 3.2 on 2021-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0004_alter_project_proj_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('org_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
