# Generated by Django 3.2 on 2021-04-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0005_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='org_name',
            new_name='organisation_name',
        ),
    ]
