# Generated by Django 3.2 on 2021-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0006_rename_org_name_account_organisation_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_aspects',
            field=models.CharField(default='img.jpg', max_length=100),
        ),
    ]
