# Generated by Django 3.2 on 2021-04-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0008_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user_feedback', models.TextField()),
                ('project_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website1.project')),
                ('user_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website1.usermodel')),
            ],
        ),
    ]
