# Generated by Django 3.2 on 2021-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(max_length=100),
        ),
    ]
