# Generated by Django 3.2 on 2021-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0010_alter_project_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drive_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
