# Generated by Django 3.2 on 2021-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0012_alter_project_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drive_link',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
