# Generated by Django 3.2 on 2021-04-24 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0013_auto_20210423_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_dept',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_role',
            field=models.CharField(default='STUDENT', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_thumbnail',
            field=models.CharField(default='img.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_designation',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY'), ('ALUMNI', 'ALUMNI'), ('PARENTS', 'PARENTS'), ('GUEST', 'GUEST')], default='STUDENT', max_length=50),
        ),
    ]
