# Generated by Django 3.2 on 2021-04-24 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0014_auto_20210424_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
