# Generated by Django 3.2 on 2021-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0015_alter_feedback_feedback_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dept',
            field=models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('MECH', 'MECH')], default='it', max_length=6),
        ),
    ]
