# Generated by Django 3.2 on 2021-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0016_alter_project_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project_dept',
            field=models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('MECH', 'MECH')], default='IT', max_length=50),
        ),
    ]
