# Generated by Django 3.2 on 2021-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0018_auto_20210424_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_category',
            field=models.CharField(choices=[('PRODUCT DEVELOPMENT', 'PRODUCT DEVELOPMENT'), ('RESEARCH BASED', 'RESEARCH BASED'), ('SUSTAINABILITY', 'SUSTAINABILITY'), ('EMERGING TECHNOLOGY', 'EMERGING TECHNOLOGY'), ('COMMUNITY WELFARE', 'COMMUNITY WELFARE')], default='PRODUCT DEVELOPMENT', max_length=50),
        ),
    ]
