# Generated by Django 3.2 on 2021-04-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0019_alter_project_proj_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.CharField(max_length=50),
        ),
    ]
