# Generated by Django 3.2 on 2021-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0020_alter_usermodel_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='org_name',
            field=models.CharField(default='DBIT', max_length=100),
        ),
    ]
