# Generated by Django 3.2 on 2021-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0021_feedback_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mem4_linkedin',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='mem4_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
