# Generated by Django 3.2 on 2021-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0022_auto_20210426_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mem4_linkedin',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='mem4_name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
