# Generated by Django 3.2 on 2021-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0024_auto_20210426_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_dept',
            field=models.CharField(default='IT', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_year',
            field=models.CharField(default='TE', max_length=100),
        ),
    ]
