# Generated by Django 4.2.5 on 2024-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0025_auto_20210428_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='organisation',
            field=models.CharField(default='DBIT', max_length=100),
        ),
    ]
